name: Terraform Destroy
#on: 
  #push: #quando ele vai rodar
    #branches:
      #- main #branch que ele vai rodar
  #workflow_dispatch: #permite executar manualmente

on:
  workflow_dispatch:

jobs:
  terraform_destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest #vai rodar numa máquina ubuntu próprio do github

    defaults:
      run:
        shell: bash #tipo de shell que vai correr o workflow na máquina

    steps:
    - name: Checkout #precisa dele em todos os steps (é padrão)
      uses: actions/checkout@v3 #padrão do github

    # Instalar Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false 

    # Configurar credenciais AWS
    - name: Configurar AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # Inicializar o Terraform
    - name: Terraform Init (Remote Backend)
      run: terraform init

    # Fazer o validate
    - name: Terraform Validate
      run: terraform validate

    # Fazer o destroy
    - name: Terraform Destroy
      env:
        AWS_KEY_PUB: ${{ secrets.AWS_KEY_PUB }}
      run: |
        terraform destroy -auto-approve -var "aws_key_pub=${{ secrets.AWS_KEY_PUB }}"